### ISSUE TITLE
Error when parsing;

### ISSUE THREAD

**Issue by dadsadrfadff** [Bakkes/CPPRP#19]
Hi,
First off, I want to thank you for making such a great parser! I’ve been using it a lot, and it’s been working really well. However, since the latest Rocket League update, I’ve been running into an issue when trying to parse a replay.
Here’s the error I’m getting:
Caught ex GeneralParseException: Property TAGame.GameEvent_TA:RichPresenceString is undefined
Parse log: T_POS=0, BIT_POS=0, ABS=0/208896. 
Version(868, 32, 10) on file "/tmp/phplmRZnn"

Thanks in advance for looking into it! :)

**Comment by Bakkes** [comment]
Could you upload the replays that break? One replay per distinct error message if there's multiple replays failing at different parts. I guess the update added a lot of info to replay files because there's a new gamemode and the online freeplay thing. Don't play the game myself anymore though so I've been relying on others to provide replay files before looking into it.

**Comment by Bakkes** [comment]
Thanks for providing those replays! The parser can now parse those two replays correctly. I've also added support for splitshot using [this replay](https://ballchasing.com/replay/3926bf27-53b0-4339-904f-207ddef60116). I'm not sure if splitshot heatseeker has additional properties because I couldn't find a replay to test.

I think this covers the 2.46 update, but do let me know if any other errors pop up.
